import { createSlice } from '@reduxjs/toolkit';

// Define initial state
const initialState = {
    isOpen: [], // for active default menu
    defaultId: 'default',
    opened: true
};

// Create the slice
const sidebarSlice = createSlice({
    name: 'sidebar', // Name of the slice
    initialState,
    reducers: {
        // Action to open a specific menu item
        menuOpen: (state, action) => {
            state.isOpen = [action.payload];
        },
        
        // Action to toggle menu visibility
        setMenu: (state, action) => {
            state.opened = action.payload;
        },
    }
});

// Export actions generated by createSlice
export const { menuOpen, setMenu } = sidebarSlice.actions;

// Export the reducer for the store
export default sidebarSlice.reducer;


// // theme constant
export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;