// import config from "../../config";

// // actionTypes - customization reducer
// export const SET_MENU = '@customization/SET_MENU';
// export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
// export const MENU_OPEN = '@customization/MENU_OPEN';
// export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
// export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';


// // theme constant
// export const gridSpacing = 3;
// export const drawerWidth = 260;
// export const appDrawerWidth = 320;

// export const initialState = {
//     isOpen: [], // for active default menu
//     defaultId: 'default',
//     fontFamily: config.fontFamily,
//     borderRadius: config.borderRadius,
//     opened: true
// };

// // ==============================|| CUSTOMIZATION REDUCER ||============================== //

// const customizationReducer = (state = initialState, action) => {
//     let id;
//     switch (action.type) {
//         case MENU_OPEN:
//             id = action.id;
//             return {
//                 ...state,
//                 isOpen: [id]
//             };
//         case SET_MENU:
//             return {
//                 ...state,
//                 opened: action.opened
//             };
//         case SET_FONT_FAMILY:
//             return {
//                 ...state,
//                 fontFamily: action.fontFamily
//             };
//         case SET_BORDER_RADIUS:
//             return {
//                 ...state,
//                 borderRadius: action.borderRadius
//             };
//         default:
//             return state;
//     }
// };

// export default customizationReducer;

import { createSlice } from '@reduxjs/toolkit';
import config from '../../config';

// Define initial state
const initialState = {
    fontFamily: config.fontFamily,
    borderRadius: config.borderRadius,
};

// Create the slice
const customizationSlice = createSlice({
    name: 'customization', // Name of the slice
    initialState,
    reducers: {
        // Action to set the font family
        setFontFamily: (state, action) => {
            state.fontFamily = action.payload;
        },

        // Action to set the border radius
        setBorderRadius: (state, action) => {
            state.borderRadius = action.payload;
        }
    }
});

// Export actions generated by createSlice
export const { setFontFamily, setBorderRadius } = customizationSlice.actions;

// Export the reducer for the store
export default customizationSlice.reducer;


// // theme constant
export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;